libp2p/universal-connectivity

rust-server/Cargo.lock, rust-server/Cargo.toml, rust-server/src/main.rs
Creating as pull request until https://github.com/libp2p/github-mgmt/pull/140 is merged.
Depend on latest commits on https://github.com/libp2p/rust-libp2p/pull/3625 more specifically
https://github.com/libp2p/rust-libp2p/pull/3625/commits/b5728952464f570c5636f5e6a4fa2448e28f3cbe resolving the missing SUBSCRIBE message previously not send by a rust-libp2p server.
Additional refactorings:
- Use clap to parse command line arguments. Among other things gives us nice help text and better error messages.
- Depend on `libp2p-webrtc` directly as we will remove the re-export from `libp2p`.
- Use `futures-timer` to send `Hello World` on a 2 second interval instead of on each `SwarmEvent`.
- Redo logging on various levels (warn, info, debug).
=> Fix missing SUBSCRIBE and refactor

go-server/.gitignore, go-server/chatroom.go, go-server/identity.go, go-server/main.go, go-server/ui.go
=> Improvements to the Go daemon

rust-server/src/main.rs
closes https://github.com/libp2p/universal-connectivity/issues/16 by reintroducing Kademlia (which was deleted as a part of https://github.com/libp2p/universal-connectivity/commit/074b3769bc9a8d2c062bc0c939373e7c6fe440aa)
=> feat: add Kademlia to rust peer

package-lock.json, packages/frontend/blockies.d.ts, packages/frontend/package.json, packages/frontend/src/components/chat.tsx
- Refactor the chat message into a separate component to allow integration of blockies in the `useEffect` hook.
- Get peer ID string of every sender and use it as a seed to each blocky.
- FIXME: TypeScript yells that 'from' doesn't exist in type 'Message', which apparently is a variant type of either 'SignedMessage' or 'UnsignedMessage', of which the first contains 'from' attribute. Currently the 'Message' is being casted as 'any' as a quick fix for this.
=> Add blocky identicons to chat message UI

packages/frontend/src/components/chat.tsx
Fixes incorrect logic where signed messages were discarded
closes https://github.com/libp2p/universal-connectivity/issues/10
=> fix: render signed messages

go-peer/main.go
Counterpart to https://github.com/libp2p/universal-connectivity/pull/27
```
➜  libp2p-lookup direct --address /ip4/127.0.0.1/udp/53681/quic-v1
Lookup for peer with id PeerId("12D3KooWAzjjDrqz4GwKzEG3DChnS7pQq1YdRfDELqG46AeiRw6m") succeeded.
Protocol version: "ipfs/0.1.0"
Agent version: "github.com/libp2p/universal-connectivity/go-peer@"
Observed address: "/ip4/127.0.0.1/udp/39383/quic-v1"
Listen addresses:
- "/ip4/192.168.2.109/udp/53681/quic-v1"
- "/ip4/127.0.0.1/udp/53681/quic-v1"
- "/ip6/2003:ea:e728:da92:b841:7b35:e403:ad83/udp/54457/quic-v1"
- "/ip6/::1/udp/54457/quic-v1"
- "/ip4/84.132.144.14/udp/53681/quic-v1"
Protocols:
- "/ipfs/ping/1.0.0"
- "/libp2p/circuit/relay/0.2.0/stop"
- "/ipfs/id/1.0.0"
- "/ipfs/id/push/1.0.0"
- "/meshsub/1.1.0"
- "/meshsub/1.0.0"
- "/floodsub/1.0.0"
- …
```
=> feat(go/kademlia): Use custom protocol

rust-peer/src/main.rs
- Use custom Kademlia protocol "/universal-connectivity/kad/1.0.0".
- Add remote peers to local Kademlia routing table.
- Regularly run Kademlia bootstrap mechanism in order for the local node to stay well connected.
Fixes #25.
=> feat(rust/kademlia): Use custom protocol and bootstrap regularly

packages/frontend/src/lib/libp2p.ts
Resolves this error:
```
common.js:113 libp2p:upgrader:error could not create new stream +0ms CodeError: Too many outbound protocol streams for protocol "/ipfs/id/push/1.0.0" - limit 1
at ConnectionImpl.newStream [as _newStream] (upgrader.js:325:1)
at async ConnectionImpl.newStream (index.js:55:1)
at async eval (index.js:99:1)
at async Promise.all (:3000/index 0)
at async IdentifyService.push (index.js:121:1)
at async IdentifyService.pushToPeerStore (index.js:140:1)
19:55:26.435 common.js:113 libp2p:identify:error could not push identify update to peer +0ms CodeError: Too many outbound protocol streams for protocol "/ipfs/id/push/1.0.0" - limit 1
at ConnectionImpl.newStream [as _newStream] (upgrader.js:325:1)
at async ConnectionImpl.newStream (index.js:55:1)
at async eval (index.js:99:1) …
```
=> fix: increase maxPushOutgoingStreams limit to resolve err

rust-peer/src/main.rs
The `.with_initial_delay(Duration::ZERO)` was causing a timeout in identify
```
[2023-04-11T03:49:49Z INFO  rust_libp2p_webrtc_peer] BehaviourEvent::Identify Error { peer_id: PeerId("12D3KooWHv4mwDZuC9mEHUmiY54ccJSTK5vfEcSwwR3VSUEcCg16"), error: Timeout }
```
removing it actually allows us to get a `BehaviourEvent::Identify Received`
=> fix: identify timeout

rust-peer/.gitignore, rust-peer/src/main.rs
Instead of hardcoding the key and certificate, attempt to read it from a known location. If it does not exist, generate it and write it to said location.
=> Generate key and certificate on startup

packages/frontend/src/lib/libp2p.ts
Since AutoNat cannot be explicitly disabled, delay its start by 1 day
=> fix: delay autonat start by 1 day

go-peer/main.go, packages/frontend/public/libp2p-hero.svg, packages/frontend/src/components/chat.tsx, packages/frontend/src/lib/libp2p.ts, packages/frontend/src/pages/index.tsx, rust-peer/src/main.rs
=> fix: added multiaddr dial box + UI fixes (#49)

.github/.dependabot.yml
This only adds the Rust configuration for now. Other teams (@libp2p/go-libp2p-maintainers & @libp2p/js-libp2p-chainsafe-maintainers) are welcome to add their desired configuration after!
=> Add dependabot file

go-peer/go.mod
bumping:
golang to 1.21
go-libp2p to v0.31.0
and life is good. I'll submit another PR later that attempts to enable WASI builds here but it's failing hard ->
after fixing imports: 
```
replace go.uber.org/fx v1.20.0 => github.com/maceip/fx v0.0.0-20230925211015-d2b444db7f67
replace github.com/libp2p/go-netroute v0.2.1 => github.com/maceip/go-netroute v0.2.2-0.20230925214737-ac11d2898240
```
and ripping out the UI code, you can compile it with:
```
GOOS=wasip1 GOARCH=wasm go build .
```
and host it via:
```
wasirun --dir . --env-inherit --trace --listen 0.0.0.0:9095 go-peer
```
but it barfs with net/fs issues .... /me sulks away
=> bump golang + go-libp2p deps

.github/workflows/ci.yml, go-peer/flag.go, go-peer/identity.go, go-peer/main.go
Resolves https://github.com/libp2p/universal-connectivity/issues/99
This PR adds Go support to the CI. It does so by reusing reusable workflows from Unified CI. We're not enlisting `universal-connectivity` for full CI because the setup here is non-common. One reason why we might have wanted to opt-in for uCI is automatic Go upgrades but it looks like we're already ahead of everything else here.
=> ci: set up CI for Go

rust-peer/Cargo.lock, rust-peer/Cargo.toml, rust-peer/src/main.rs
We assume that the bootstrap node runs on its own machine and can consume as (almost) as much RAM as it can get. Thus, once we reach 90% RAM usage, we deny any further incoming connections.
=> feat(rust): add memory-based connection limits

go-peer/main.go, js-peer/src/lib/libp2p.ts, rust-peer/src/main.rs
This PR changes the protocol ID used by the app to use the IPFS Kademlia DHT.
- Why was a separate DHT id created for this app in the first place?
- What are the implications of using the IPFS DHT for this app if the presumption is that most users are browser users anyways
**Resolving bootstrap node PeerIDs to multiaddrs:** My original thinking was that the DHT would be used to make it easier to discover the multiaddrs of deployed Rust and Go peers which have an ephemeral (because of the temp cert which rotates) WebRTC-direct and WebTransport multiaddrs. That way, we can avoid [hardcoding ephemeral multiaddrs](https://github.com/libp2p/universal-connectivity/blob/use-ipfs-dht/js-peer/src/lib/constants.ts#L7-L8) in the frontend and instead just hardcode the PeerIDs which would be looked up …
=> feat: use ipfs dht

go-peer/main.go
this should help browser peers establish direct p2p connections through
the circuit relay v2 reservation
=> feat: enable circuit relay v2 in go peer

rust-peer/src/main.rs
Allow hosts that only connect to the rust peer to find each other over gossipsub
=> feat: rust peer joins peer discovery topic

js-peer/src/lib/libp2p.ts
- Connect to the boostrapper only with ipv4 and websockets
- Remove the boostrap config. libp2p will connect to the peer anyways through the relayListenAddrs.
=> fix: only set circuit relay listen and simplify
